import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { Courgette } from "@next/font/google";

const courgette = Courgette({ weight: "400", subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="index__header">
        <div className={courgette.className}>
          <h1>Hi, I{"'"}m Josu&eacute;.</h1>
          <p>
            I{"'"}m a Software engineer based in New York with 5 years of
            professional experience in Engineering and IT.
          </p>
          <p>Welcome. Have a look around!</p>
        </div>
      </div>
      <Image
        className="index__image"
        src="/images/placeholder1.jpg"
        alt=""
        width={500}
        height={300}
      />
    </>
  );
}
